trigger:
  batch: true
  branches:
    include:
    - master
    - release/3.0

pr:
- master
- release/3.0
- dev/arcade-migration

name: $(Date:yyyyMMdd)$(Rev:.rr)

variables:
  - name: TeamName
    value: dotnet-core-acquisition
  # Skip Running CI tests
  - name: SkipTests
    value: true
  # Set Official Build Id
  - name: OfficialBuildId
    value: 20190628.11

  # Produce test-signed build for PR and Public builds
  - ${{ if or(eq(variables['System.TeamProject'], 'public'), in(variables['Build.Reason'], 'PullRequest')) }}:
    - name: SignType
      value: test

  # Set publish variables only for non-PR build from internal
  - ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
    - name: SignType
      value: $[ coalesce(variables.OfficialSignType, 'real') ]
    # Only get the secret variable groups if the def has the official name. Allows dev build defs.
    - ${{ if eq(variables['Build.DefinitionName'], 'dotnet-core-setup') }}:
      # # Variable groups containing official build publish info.
      # - group: DotNet-Blob-Feed
      - group: DotNet-Symbol-Server-Pats
      # # Used for publishing individual leg assets to azure blob storage
      # - group: DotNet-DotNetCli-Storage
      # Used for dotnet/versions update
      # - group: DotNet-Versions-Publish

  # Inter-job publish variables.
  # Custom values override official if provided.
  - name: _AzureAccountName
    value: $[ coalesce(variables.AzureAccountName, 'dotnetcli') ]
  - name: _ContainerName
    value: $[ coalesce(variables.ContainerName, 'dotnet') ]
  - name: _AzureAccessToken
    value: $[ coalesce(variables.AzureAccessToken, '$(dotnetcli-storage-key)') ]
  - name: _ChecksumAzureAccountName
    value: $[ coalesce(variables.ChecksumAzureAccountName, 'dotnetclichecksums') ]
  - name: _ChecksumContainerName
    value: $[ coalesce(variables.ChecksumContainerName, 'dotnet') ]
  - name: _ChecksumAzureAccessToken
    value: $[ coalesce(variables.ChecksumAzureAccessToken, '$(dotnetclichecksums-storage-key)') ]

  - name: _CommonPublishArgs
    value: >-
      /p:AzureAccountName=$(_AzureAccountName)
      /p:ContainerName=$(_ContainerName)
      /p:AzureAccessToken=$(_AzureAccessToken)
      /p:ChecksumAzureAccountName=$(_ChecksumAzureAccountName)
      /p:ChecksumContainerName=$(_ChecksumContainerName)
      /p:ChecksumAzureAccessToken=$(_ChecksumAzureAccessToken)

jobs:

################################################################################
# Publish official build
################################################################################
- ${{ if and(ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  # Finalize build publish
  - template: /eng/jobs/finalize-publish.yml
    parameters:
      _PublishType: nopublishtype
  
  # Publish to dotnet/versions
  - template: /eng/jobs/finalize-publish-versions.yml
    parameters:
      DependsOn:
      - Finalize_Publish

  # Publish to Build Asset Registry
  # - template: /eng/common/templates/job/publish-build-assets.yml
  #   parameters:
  #     pool:
  #       name: NetCoreInternal-Int-Pool
  #       queue: buildpool.windows.10.amd64.vs2017
  #     dependsOn:
  #       - Finalize_Publish
